import { createFileRoute } from "@tanstack/react-router";
import { PageIntro, PageShell } from "@/components/ace-site";
import { pageHead } from "@/lib/seo";
export const Route = createFileRoute("/about")({ head: () => pageHead("About | Ashford Community Energy", "Learn how Ashford Community Energy is being developed around community benefit, evidence-led projects, collaboration and local skills.", "/about"), component: AboutPage });
function AboutPage() { return <PageShell>
  <PageIntro eyebrow="About ACE" title="Energy projects built around community benefit"><p>Ashford Community Energy exists to develop and support renewable energy, energy efficiency and carbon-reduction projects for community benefit.</p></PageIntro>
  <section className="ace-editorial-split"><div><h2>Our purpose</h2></div><div className="ace-prose"><p>ACE aims to help local communities move towards a low-carbon, affordable and sustainable future. That means looking for practical opportunities to generate cleaner energy, reduce energy use and make local energy infrastructure more resilient.</p><p>The model is community-led and commercially grounded. Projects need to make sense technically and financially while keeping community benefit at the centre of the decision.</p></div></section>
  <section className="ace-principles"><h2>How we intend to work</h2><div className="ace-principle-list"><article><span>01</span><h3>Community led</h3><p>A board that reflects local interests and designs activity around community benefit.</p></article><article><span>02</span><h3>Evidence led</h3><p>Use local knowledge alongside open data, energy planning resources and professional expertise.</p></article><article><span>03</span><h3>Collaborative</h3><p>Work with local authorities, organisations, communities, businesses and specialist partners.</p></article><article><span>04</span><h3>Reinvesting benefit</h3><p>Use surplus to help develop and widen the reach of the society's core community objectives.</p></article></div></section>
  <section className="ace-image-panel"><img src="/assets/content/community-solar.webp" alt="Community members outside a building with rooftop solar" /><div><h2>Local knowledge matters</h2><p>The strongest opportunities often start with someone who knows a building, a need or a local connection. ACE provides a route for those ideas to be explored systematically.</p><a href="/contact#contact-form" className="ace-about-contact">Suggest a site</a></div></section>
</PageShell>; }
