import { createFileRoute, Link } from "@tanstack/react-router";
import { PageIntro, PageShell } from "@/components/ace-site";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/governance")({
  head: () => pageHead("Governance and policies | Ashford Community Energy", "Ashford Community Energy governance principles, transparency commitments, legal-status disclosures and website policies.", "/governance"),
  component: GovernancePage,
});

function GovernancePage() {
  return <PageShell><PageIntro eyebrow="Governance & policies" title="Trust needs visible rules and evidence"><p>ACE is being developed around community benefit, clear project status and an evidence-led approach. This page is the permanent home for governance and policy information.</p></PageIntro><section className="ace-governance-principles"><article><span>01</span><h2>Community-led governance</h2><p>The stated model is for a board that reflects local interests and ensures activities are designed and delivered for community benefit.</p></article><article><span>02</span><h2>Evidence-led decisions</h2><p>Local knowledge should be combined with open data, energy-planning resources and appropriate professional expertise before projects progress.</p></article><article><span>03</span><h2>Transparent project status</h2><p>ACE will distinguish between opportunities being explored and projects that are assessed, developed, delivered or operational. We will not present an unverified opportunity as a completed project.</p></article><article><span>04</span><h2>Community benefit and surplus</h2><p>The stated aim is to use surplus to further ACE's objectives, including new community-benefit activity, grants, skills and wider reach, subject to project and governance obligations.</p></article></section><section className="ace-legal-status"><div><h2>Legal status disclosure</h2><p>ACE's current working material is based on a Community Benefit Society application. We will publish the formal registered society name, FCA registration number and registered office here and in the site footer only once those details are formally confirmed.</p><p>This site does not make an investment offer. Any future community investment opportunity would be governed by its own formal documentation.</p></div><div className="ace-policy-index"><h2>Website policies</h2><Link to="/privacy">Privacy notice <span>→</span></Link><Link to="/cookies">Cookie notice <span>→</span></Link><Link to="/accessibility">Accessibility statement <span>→</span></Link><Link to="/website-terms">Website terms <span>→</span></Link></div></section><section className="ace-transparency-note"><h2>What will be added as ACE formalises</h2><p>Once approved and available, this area can hold the society's governing rules, annual reports and accounts, AGM information, relevant policies and other documents that members and the wider community should be able to inspect.</p></section></PageShell>;
}
