import { createFileRoute, Link } from "@tanstack/react-router";
import { PageIntro, PageShell } from "@/components/ace-site";
import { pageHead } from "@/lib/seo";

export const Route = createFileRoute("/website-terms")({
  head: () => pageHead("Website terms | Ashford Community Energy", "Terms for using the Ashford Community Energy website, including project-status, investment and general-information disclaimers.", "/website-terms", true),
  component: TermsPage,
});

function TermsPage() {
  return <PageShell><PageIntro eyebrow="Website terms" title="Using this website"><p>These terms explain the basis on which information is provided through the ACE website while the organisation and its community-energy pipeline develop.</p></PageIntro><section className="ace-legal-copy"><p className="ace-policy-date">Last reviewed: 17 September 2026</p><h2>1. General information</h2><p>The website is provided to explain Ashford Community Energy's purpose, emerging project approach and ways to make contact. Content is general information and should not be treated as legal, tax, technical, financial or investment advice.</p><h2>2. No investment offer</h2><p>Nothing on this website is an invitation, recommendation or offer to buy shares, lend money or make another investment. Any future community investment opportunity would be described in separate formal documentation with its own terms and risk information.</p><h2>3. Project status</h2><p>A site or opportunity shown as Exploring or Assessing is not a committed project. Technical feasibility, ownership, permissions, grid matters, funding, contracts and other dependencies may prevent an opportunity from proceeding.</p><h2>4. Accuracy and updates</h2><p>ACE aims to keep information clear and current but the website will change as projects, governance arrangements and evidence develop. If a material decision depends on information shown here, contact ACE for the latest position.</p><h2>5. External links</h2><p>The website may link to third-party websites for useful background information. ACE is not responsible for the content, security or privacy practices of those external sites.</p><h2>6. Intellectual property</h2><p>Unless otherwise stated, website text, design and ACE-created materials may not be reproduced for commercial use without permission. You may link to public pages and quote brief extracts with appropriate attribution.</p><h2>7. Privacy and cookies</h2><p>Use of personal information and browser storage is explained in the <Link to="/privacy">Privacy Notice</Link> and <Link to="/cookies">Cookie Notice</Link>.</p><h2>8. Governing law</h2><p>These website terms are intended to be governed by the laws of England and Wales. They do not replace the governing rules, contracts or formal offer documents that may apply to ACE or any future project.</p></section></PageShell>;
}
